[MESSAGES]
WELCOME = '¡Hola! Escribi /help si no sabes los comandos'

DIFUSION = """
Grupo para tareas de difusión de charlas de matematica:\
https://t.me/joinchat/DLkiixM8QHt53Al_5ZYDjA \n\
Canal de Youtube con contenido de charlas y coloquios:\
https://www.youtube.com/channel/\
UCaP4UdjleezecVaXBa7spkw/videos?app=desktop
                  """

HELP = """
/aplicada Correlativas en la orientación aplicada \n\
/comedor Muestra el menu del mes \n\
/difusion Grupo de difusión \n\
/help Muestra este bonito mensaje \n\
/online Dice si el Bot esta vivo \n\
/listar Muestra los grupos de materias \n\
/listaroptativas Muestra los grupos de materias optativas \n\
/listarotros Muestra otros grupos \n\
/pura Correlativas en la orientación pura \n\
               """

ONLINE = "Estoy con vida"

[BOT]
TOKEN = "1388812051:AAGUR4Z8u8kPQueHH_aHJD3tfPph21BK3NU"
